version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_PROXY_HOST=proxysql
      - DB_PROXY_PORT=6033
    depends_on:
      - proxysql

  proxysql:
    image: proxysql/proxysql
    ports:
      - "6033:6033"
      - "6032:6032"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./proxysql.cnf:/proxysql/proxysql.cnf

  mariadb1:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=one_id
    volumes:
      - mariadb1-data:/var/lib/mysql

  mariadb2:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=one_id
    volumes:
      - mariadb2-data:/var/lib/mysql

volumes:
  mariadb1-data:
  mariadb2-data:
